### ISSUE TITLE
'NoneType' object has no attribute 'count' with custom_multichannels

### ISSUE THREAD

**Issue by jtilly** [mamba-org/mamba#1352]
We're using (abusing?) `custom_multichannels` to rename channels. That way a user can do

```
mamba install some-channel::pandas
```
even if `some-channel` is only made available through some artifactory by a different name.

This works with conda (and it used to work with mamba<0.15). 

Example `.condarc`:

```
channels:
  - conda-forge
custom_multichannels:
  conda-forge2:  # this is fake channel that is just "renaming" conda-forge
   - conda-forge
```

When I run

```
mamba install conda-forge2::pandas
```

with mamba 0.19.1, I get:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/mamba.py", line 927, in exception_converter
        raise e
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/mamba.py", line 921, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/mamba.py", line 879, in _wrapped_main
        result = do_call(args, p)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/mamba.py", line 757, in do_call
        exit_code = install(args, parser, "install")
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/mamba.py", line 534, in install
        index = load_channels(pool, channels, repos)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/utils.py", line 123, in load_channels
        index = get_index(
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/utils.py", line 77, in get_index
        all_channels = list(map(fixup_channel_spec, all_channels))
      File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/mamba/utils.py", line 65, in fixup_channel_spec
        at_count = spec.count("@")
    AttributeError: 'NoneType' object has no attribute 'count'

`$ /usr/local/Caskroom/miniconda/base/condabin/mamba install -vvv conda-forge2::pandas`
```

With conda, it works:

```
conda install conda-forge2::pandas
```

produces

```
% conda install conda-forge2::pandas  
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/mamba-debug

  added / updated specs:
    - conda-forge2::pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-1.3.5               |   py39h4d6be9b_0        11.7 MB  conda-forge2
    ------------------------------------------------------------
                                           Total:        11.7 MB
```

Note that `mamba install -c conda-forge2 pandas` also works.

**Comment by jonashaag** [comment]
Problem is that here https://github.com/mamba-org/mamba/blob/bab7ae50d75f067c493b8d0cd065ea29bd3f9e8c/mamba/mamba/mamba.py#L372 `base_url` is `None`

**Comment by jtilly** [comment]
I can patch on the Python side could look like this (though I'm not _really_ sure what I'm doing):

```
diff --git a/mamba/mamba/mamba.py b/mamba/mamba/mamba.py
index 427fab5..30cd6c5 100644
--- a/mamba/mamba/mamba.py
+++ b/mamba/mamba/mamba.py
@@ -369,8 +369,12 @@ def install(args, parser, command="install"):
     for spec in specs:
         # CONDA TODO: correct handling for subdir isn't yet done
         spec_channel = spec.get_exact_value("channel")
-        if spec_channel and spec_channel.base_url not in channels:
+        if spec_channel and spec_channel.base_url and spec_channel.base_url not in channels:
             channels.append(spec_channel.base_url)
+        elif spec_channel and spec_channel._channels:
+            for _channel in spec_channel._channels:
+                if _channel.base_url not in channels:
+                    channels.append(_channel.base_url)
 
     index_args["channel_urls"] = channels
```
I'm adding the channels listed in multichannels to `channels`.

But then the solver still prints the following error:
```
error    Selected channel specific (or force-reinstall) job, but package is not available from channel. Solve job will fail.
```
It doesn't _fail_ though (i.e. it has exit code 0).

**Comment by jonashaag** [comment]
@jtilly Does #1505 fix our issues?

**Comment by jtilly** [comment]
Yes, this works with `mamba>=0.23`. Thank you for the fix, @wolfv!
